### ISSUE TITLE
Plans for this project?

### ISSUE THREAD

**Issue by mholt** [everyday/certd#1]
I just found this doing a search for "certd" since I was thinking of renaming my [certs](https://github.com/mholt/certs) program to certsd or certd. Was wondering what your plans are for this repo and maybe if you'd like to join efforts.

**Comment by fabpopa** [comment]
Hey Matt, great work on Caddy! The idea so far is to always give certd a list of domains to monitor, a list of local directories to put the respective certs in, and an external object store like S3 to back up identity keys and certs to. I think it shouldn't run without those details. Then it operates in two modes: 1) one-time invocation to verify a new domain, and 2) daemon that wakes up at a random time daily and checks if there's a newer cert for its monitored domains in the object store or renews and puts certs there for itself and others. This should solve single- as well as multi-server TLS termination setups. Would something like this help you?

**Comment by mholt** [comment]
Thanks!

Yes, it would. The basic idea sounds the same, with some implementation and philosophical differences. Here are some of my thoughts:

- Two modes (a one-time invocation to obtain certs, and a long-running daemon to maintain) - same!
- Give a list of domains to obtain - same!
- Put obtained certificates, organized, into a folder - same!
- However, for monitoring the certificates for renewals, I prefer the idea of traversing on a regular basis the folder that stores the certificates. This way certs can be added without having to update a config somewhere. Or, probably better yet:
- A simple database like [BoltDB](https://github.com/boltdb/bolt) to map hostnames to certificate files and maybe keep expiration dates handy too (parsing certs can be slow on some architectures). I think this is needed since SAN certificates can have up to 100 names in them.
- I've talked to a few people who use Let's Encrypt pretty heavily already (nothing on the scale of [WordPress.com getting a million certs in a day](https://twitter.com/vtlynch/status/692878464941051904), but...) and some of the primary demands are for obtaining SAN certificates in bulk with potentially different challenge types and/or DNS providers. My tool meets this demand halfway by using a CSV file as input but it needs more development to customize each domain as desired.

What language were you planning to use?

> checks if there's a newer cert for its monitored domains in the object store or renews and puts certs there for itself and others

This'll get complicated to do correctly really quickly. I was thinking of just keeping the certificates on the machine running the daemon and serving an authenticated API (over HTTPS, of course, maybe using TLS client auth) to be able to request certs and keys as needed. I can understand wanting a decentralized solution but if you/we go that route, it needs much more detailed discussion I think.

Sounds fun though, I'm looking forward to this. Having written some of this already for Caddy, I've learned a little about the process, so I'm looking for ways to extract that obtain+manage code into a more general, useful library that maybe Caddy could import and use instead one day.

**Comment by fabpopa** [comment]
Thanks very much for the insight!

I think automation would be best achieved with individual certs. The SAN use case and the multiple domain challenge types would certainly be useful, but I'm betting it's for a minority and could probably be re-engineered around individual certs just as well.

Since domain validation has to be done locally, I thought: Why not do all operations locally too? That works if everyone shares the same object bucket. Otherwise it would have to be the kind of client-server setup you laid out.

For my purposes and time frame, the object approach would work better, but I am happy to rename the repo to something else if you'd like to establish "certd" as a more generic solution.

**Comment by mholt** [comment]
> I think automation would be best achieved with individual certs.

I actually agree. SAN is most useful when you have some manual steps in your deployment and want to consolidate files. I've already had requests for Caddy to use it, but I discovered early on that individual (non-SAN) certificates are much easier to manage in automation. My tool already does, however, make SAN certificates if the user forms their input that way. It puts it into a folder keyed by the common name.

> For my purposes and time frame, the object approach would work better, but I am happy to rename the repo to something else if you'd like to establish "certd" as a more generic solution.

I get it -- that makes sense. Perhaps instead of locking the user into using S3, make that feature optional or pluggable with different providers. If it's going to be locked in with S3 or just one workflow, it sounds like a more specific tool than what I had in mind, which hopefully will take a more generic approach. Like curl is to URL-related things, I hope certd/certs (or whatever the final name is) will also be a generic tool. With the ability to layer specific workflows on top.

What language were you planning to use? Go or something else?

**Comment by fabpopa** [comment]
> Perhaps instead of locking the user into using S3, make that feature optional or pluggable with different providers.

Absolutely! Any ideas for a nice plugin model here?

> What language were you planning to use? Go or something else?

Yup, it would be in Go.

**Comment by mholt** [comment]
Nice, Go's a great language for this.

> Absolutely! Any ideas for a nice plugin model here?

On a library/design level, it's just a matter of using interfaces when you want to be able to swap out implementations/integrations. Of course, using the different ones requires compiling the program with those customizations. That's what I've typically done and it's worked out well, but I'm sure whatever you choose will be good too. :smile:

**Comment by mholt** [comment]
FYI I've started stubbing out plans over here: https://github.com/mholt/certs

Would love to have your feedback and, time permitting, cooperation to build this. Notice the two 'modes' it can be run in (certs and certsd).

**Comment by fabpopa** [comment]
Looks good, I'll close this repo. Have been using [acmetool](https://github.com/hlandau/acme) for now.
